# Generated by Django 5.2.7 on 2025-10-11 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DietPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('goal', models.CharField(choices=[('BUK', 'Bulking'), ('CUT', 'Cutting'), ('MAINT', 'Maintenance')], max_length=5)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('calories', models.IntegerField(help_text='Calories per 100g')),
                ('protein', models.FloatField(help_text='Protein per 100g')),
                ('carbs', models.FloatField(help_text='Carbs per 100g')),
                ('fats', models.FloatField(help_text='Fats per 100g')),
                ('category', models.CharField(choices=[('FRT', 'Fruit'), ('VEG', 'Vegetable'), ('GRN', 'Grain'), ('PRN', 'Protein'), ('DRY', 'Dairy'), ('FAT', 'Fat & Oil'), ('OTH', 'Other')], max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('time', models.TimeField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MealFoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('unit', models.CharField(choices=[('g', 'grams'), ('oz', 'ounces'), ('ml', 'milliliters'), ('cup', 'cup(s)'), ('slice', 'slice(s)'), ('unit', 'unit(s)')], default='g', max_length=10)),
            ],
        ),
    ]
