# Generated by Django 5.2.7 on 2025-10-11 20:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dietplan',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_diet_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diet_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meal',
            name='diet_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='diet.dietplan'),
        ),
        migrations.AddField(
            model_name='mealfooditem',
            name='food_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='diet.fooditem'),
        ),
        migrations.AddField(
            model_name='mealfooditem',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diet.meal'),
        ),
        migrations.AddField(
            model_name='meal',
            name='food_items',
            field=models.ManyToManyField(related_name='meals', through='diet.MealFoodItem', to='diet.fooditem'),
        ),
        migrations.AlterUniqueTogether(
            name='mealfooditem',
            unique_together={('meal', 'food_item')},
        ),
    ]
