# Generated by Django 5.2.7 on 2025-10-15 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dietplan',
            old_name='user',
            new_name='student',
        ),
    ]
