# Generated by Django 5.2.7 on 2025-11-06 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0003_rename_user_dietplan_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('consumed_at', models.DateTimeField(auto_now_add=True)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='diet.meal')),
            ],
            options={
                'unique_together': {('meal', 'date')},
            },
        ),
    ]
