# Generated by Django 5.2.7 on 2025-11-07 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0004_mealregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietplan',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='target_calories',
            field=models.IntegerField(blank=True, help_text='Target daily calories', null=True),
        ),
    ]
