# Generated by Django 5.2.7 on 2025-10-28 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_appointment_scheduleexception_scheduleteacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='CREF',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
