# Generated by Django 5.2.7 on 2025-11-07 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_progresslog_height'),
        ('teachers', '0004_teacher_cref'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherStudents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='student.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='teachers.teacher')),
            ],
            options={
                'verbose_name': 'Aluno do Professor',
                'verbose_name_plural': 'Alunos do Professor',
                'unique_together': {('teacher', 'student')},
            },
        ),
    ]
