# Generated by Django 5.2.7 on 2025-11-07 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0005_teacherstudents'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_initial_photos', models.BooleanField(default=False)),
                ('initial_photos_date', models.DateTimeField(blank=True, null=True)),
                ('has_diet_plan', models.BooleanField(default=False)),
                ('diet_plan_date', models.DateTimeField(blank=True, null=True)),
                ('has_training_plan', models.BooleanField(default=False)),
                ('training_plan_date', models.DateTimeField(blank=True, null=True)),
                ('has_progress_log', models.BooleanField(default=False)),
                ('progress_log_date', models.DateTimeField(blank=True, null=True)),
                ('has_body_measurements', models.BooleanField(default=False)),
                ('body_measurements_date', models.DateTimeField(blank=True, null=True)),
                ('evaluation_completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher_student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='teachers.teacherstudents')),
            ],
        ),
    ]
