# Generated by Django 5.2.7 on 2025-10-15 22:50

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exerciselog',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='setlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setlog',
            name='is_pr',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
            preserve_default=False,
        ),
    ]
