# Generated by Django 5.2.7 on 2025-10-16 02:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodymeasurement',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='personalrecord',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='progressphoto',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='progressphoto',
            name='photo_type',
            field=models.CharField(choices=[('FRONT', 'Front'), ('SIDE', 'Side'), ('BACK', 'Back')], max_length=10),
        ),
    ]
