# Generated by Django 5.2.7 on 2025-11-13 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='is_program',
            field=models.BooleanField(default=False, help_text='True if this is part of a training program (ABC, Upper/Lower, etc.)'),
        ),
    ]
