# Generated by Django 5.2.7 on 2025-11-13 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0006_studentevaluation'),
        ('training', '0002_training_is_program'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='is_program',
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Program name (e.g., ABC, Upper Lower)', max_length=100)),
                ('description', models.TextField()),
                ('goal', models.CharField(choices=[('STR', 'Strength'), ('HYP', 'Hypertrophy'), ('END', 'Endurance'), ('WL', 'Weight Loss'), ('GEN', 'General Fitness')], max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='teachers.teacher')),
            ],
        ),
        migrations.AddField(
            model_name='training',
            name='program',
            field=models.ForeignKey(blank=True, help_text='If part of a program, link to the program', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='training.program'),
        ),
    ]
