# Generated by Django 5.2.7 on 2025-10-18 02:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_progresslog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progresslog',
            name='bodyfat_percentage',
        ),
        migrations.RemoveField(
            model_name='progresslog',
            name='image',
        ),
        migrations.AddField(
            model_name='progresslog',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
