# Generated by Django 5.2.7 on 2025-10-26 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_remove_progresslog_bodyfat_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='progresslog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
