# Generated by Django 5.2.7 on 2025-11-02 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_student_phone_number_alter_progresslog_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='progresslog',
            name='body_fat_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='progresslog',
            name='imc',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
