# Generated by Django 5.2.7 on 2025-11-06 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_progresslog_body_fat_percentage_progresslog_imc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='progresslog',
            old_name='weight',
            new_name='current_weight',
        ),
        migrations.RemoveField(
            model_name='student',
            name='height',
        ),
        migrations.RemoveField(
            model_name='student',
            name='weight',
        ),
        migrations.AddField(
            model_name='progresslog',
            name='goal_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='progresslog',
            name='start_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PhotosStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='student_photos/')),
                ('description', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('position', models.CharField(choices=[('front', 'Front'), ('side', 'Side'), ('back', 'Back')], max_length=10)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='student.student')),
            ],
        ),
    ]
