# Generated by Django 5.2.7 on 2025-11-07 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_rename_weight_progresslog_current_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='progresslog',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
