# Generated by Django 5.2.7 on 2025-11-14 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '0006_studentevaluation'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('video_file', models.FileField(upload_to='video_lessons/')),
                ('url_youtube', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('teoria', 'Teoria'), ('tecnica', 'Técnica'), ('pratica', 'Prática'), ('nutricao', 'Nutrição'), ('cutting', 'Cutting'), ('bulking', 'Bulking'), ('nutricao_esportiva', 'Nutrição Esportiva'), ('suplementacao', 'Suplementação'), ('recuperacao', 'Recuperação Muscular'), ('mobilidade', 'Alongamento e Mobilidade')], default='teoria', max_length=32)),
                ('state', models.BooleanField(blank=True, default=True, null=True)),
                ('for_all', models.BooleanField(blank=True, default=False, null=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_lessons', to='teachers.teacher')),
            ],
        ),
    ]
