# Generated by Django 5.2.7 on 2025-11-14 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoLesson', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videolesson',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='video_lessons/'),
        ),
    ]
