# Generated by Django 5.2.7 on 2025-11-18 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_exerciseimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='category',
            field=models.CharField(choices=[('powerlifting', 'Powerlifting'), ('strength', 'Strength'), ('stretching', 'Stretching'), ('cardio', 'Cardio'), ('olympic weightlifting', 'Olympic Weightlifting'), ('strongman', 'Strongman'), ('plyometrics', 'Plyometrics')], default='strength', max_length=50),
        ),
        migrations.AddField(
            model_name='exercise',
            name='equipment',
            field=models.CharField(blank=True, choices=[('medicine ball', 'Medicine Ball'), ('dumbbell', 'Dumbbell'), ('body only', 'Body Only'), ('bands', 'Bands'), ('kettlebells', 'Kettlebells'), ('foam roll', 'Foam Roll'), ('cable', 'Cable'), ('machine', 'Machine'), ('barbell', 'Barbell'), ('exercise ball', 'Exercise Ball'), ('e-z curl bar', 'E-Z Curl Bar'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='force',
            field=models.CharField(blank=True, choices=[('static', 'Static'), ('pull', 'Pull'), ('push', 'Push')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('expert', 'Expert')], default='beginner', max_length=20),
        ),
        migrations.AddField(
            model_name='exercise',
            name='mechanic',
            field=models.CharField(blank=True, choices=[('isolation', 'Isolation'), ('compound', 'Compound')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='primary_muscles',
            field=models.CharField(default='general', help_text='Comma-separated list of primary muscles', max_length=255),
        ),
        migrations.AddField(
            model_name='exercise',
            name='secondary_muscles',
            field=models.CharField(blank=True, default='', help_text='Comma-separated list of secondary muscles', max_length=255),
        ),
    ]
